[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32G474RETx" # to list chips, run `probe-run --list-chips.`

rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=--nmagic",
]

[build]
target = "thumbv7em-none-eabihf"

[alias]
rb = "run --bin"
rrb = "run --release --bin"
rr = "run --release"
br = "build --release"